
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sistema(object):
    def setupUi(self, Sistema):
        Sistema.setObjectName("Sistema")
        Sistema.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 202, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 202, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 234, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(148, 202, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(57, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        Sistema.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(Sistema)
        self.centralwidget.setObjectName("centralwidget")
        Sistema.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Sistema)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setDefaultUp(True)
        self.menubar.setObjectName("menubar")
        self.Registro = QtWidgets.QMenu(self.menubar)
        self.Registro.setObjectName("Registro")
        self.menuConsulta = QtWidgets.QMenu(self.menubar)
        self.menuConsulta.setObjectName("menuConsulta")
        self.menuReporte = QtWidgets.QMenu(self.menubar)
        self.menuReporte.setObjectName("menuReporte")
        self.menuSesi_n = QtWidgets.QMenu(self.menubar)
        self.menuSesi_n.setObjectName("menuSesi_n")
        Sistema.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Sistema)
        self.statusbar.setObjectName("statusbar")
        Sistema.setStatusBar(self.statusbar)
        self.actionEvaluaciones_Hist_ricas = QtWidgets.QAction(Sistema)
        self.actionEvaluaciones_Hist_ricas.setEnabled(False)
        self.actionEvaluaciones_Hist_ricas.setObjectName("actionEvaluaciones_Hist_ricas")
        self.actionDetalles_Carrera = QtWidgets.QAction(Sistema)
        self.actionDetalles_Carrera.setEnabled(False)
        self.actionDetalles_Carrera.setObjectName("actionDetalles_Carrera")
        self.actionEvaluaciones_Realizadas = QtWidgets.QAction(Sistema)
        self.actionEvaluaciones_Realizadas.setEnabled(False)
        self.actionEvaluaciones_Realizadas.setObjectName("actionEvaluaciones_Realizadas")
        self.actionResultados = QtWidgets.QAction(Sistema)
        self.actionResultados.setEnabled(False)
        self.actionResultados.setObjectName("actionResultados")
        self.actionEvaluaci_n = QtWidgets.QAction(Sistema)
        self.actionEvaluaci_n.setEnabled(False)
        self.actionEvaluaci_n.setObjectName("actionEvaluaci_n")
        self.actionCriterio = QtWidgets.QAction(Sistema)
        self.actionCriterio.setEnabled(False)
        self.actionCriterio.setObjectName("actionCriterio")
        self.actionResumen_Resultados = QtWidgets.QAction(Sistema)
        self.actionResumen_Resultados.setEnabled(False)
        self.actionResumen_Resultados.setObjectName("actionResumen_Resultados")
        self.actionEvaluaciones_por_Fecha = QtWidgets.QAction(Sistema)
        self.actionEvaluaciones_por_Fecha.setEnabled(False)
        self.actionEvaluaciones_por_Fecha.setObjectName("actionEvaluaciones_por_Fecha")
        self.actionSalir = QtWidgets.QAction(Sistema)
        self.actionSalir.setObjectName("actionSalir")
        self.Registro.addAction(self.actionEvaluaci_n)
        self.Registro.addAction(self.actionCriterio)
        self.menuConsulta.addAction(self.actionDetalles_Carrera)
        self.menuConsulta.addAction(self.actionEvaluaciones_Hist_ricas)
        self.menuConsulta.addAction(self.actionEvaluaciones_Realizadas)
        self.menuConsulta.addAction(self.actionResultados)
        self.menuReporte.addAction(self.actionEvaluaciones_por_Fecha)
        self.menuReporte.addAction(self.actionResumen_Resultados)
        self.menuSesi_n.addAction(self.actionSalir)
        self.menubar.addAction(self.Registro.menuAction())
        self.menubar.addAction(self.menuConsulta.menuAction())
        self.menubar.addAction(self.menuReporte.menuAction())
        self.menubar.addAction(self.menuSesi_n.menuAction())

        self.retranslateUi(Sistema)
        QtCore.QMetaObject.connectSlotsByName(Sistema)
        self.actionSalir.triggered.connect(QtWidgets.QApplication.quit)

    def retranslateUi(self, Sistema):
        _translate = QtCore.QCoreApplication.translate
        Sistema.setWindowTitle(_translate("Sistema", "MainWindow"))
        self.Registro.setTitle(_translate("Sistema", "Registro"))
        self.menuConsulta.setTitle(_translate("Sistema", "Consulta"))
        self.menuReporte.setTitle(_translate("Sistema", "Reporte"))
        self.menuSesi_n.setTitle(_translate("Sistema", "Sesión"))
        self.actionEvaluaciones_Hist_ricas.setText(_translate("Sistema", "Evaluaciones Históricas"))
        self.actionDetalles_Carrera.setText(_translate("Sistema", "Detalles Carrera"))
        self.actionEvaluaciones_Realizadas.setText(_translate("Sistema", "Evaluaciones Realizadas"))
        self.actionResultados.setText(_translate("Sistema", "Resultados"))
        self.actionEvaluaci_n.setText(_translate("Sistema", "Evaluación"))
        self.actionCriterio.setText(_translate("Sistema", "Criterio"))
        self.actionResumen_Resultados.setText(_translate("Sistema", "Resumen Resultados"))
        self.actionEvaluaciones_por_Fecha.setText(_translate("Sistema", "Evaluaciones por Fecha"))
        self.actionSalir.setText(_translate("Sistema", "Salir"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sistema = QtWidgets.QMainWindow()
    ui = Ui_Sistema()
    ui.setupUi(Sistema)
    Sistema.show()
    sys.exit(app.exec_())
